# Variant 9

1. Вводиться число n. Вивести масив розміру n×n, в
якому по діагоналі йдуть числа від 1 до n, а інші числа дорівнюють 0.

In [69]:
import numpy as np
n = int(input("Enter size of matrix: "))
def t1np():
    matrix = np.zeros((n, n))
    for i in range(n):
        matrix[i][i] = i+1

    print(matrix)

def t1py():
    matrix = [[0 for i in range(n)] for j in range(n)]
    for i in range(n):
        matrix[i][i] = i + 1

    for i in range(n):
        for j in range(n):
            print(matrix[i][j], end=" ")
        print()
        
t1np()
t1py()
%timeit t1np
%timeit t1py

Enter size of matrix: 11
[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  2.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  3.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  4.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  5.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  6.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  7.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  8.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  9.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 11.]]
1 0 0 0 0 0 0 0 0 0 0 
0 2 0 0 0 0 0 0 0 0 0 
0 0 3 0 0 0 0 0 0 0 0 
0 0 0 4 0 0 0 0 0 0 0 
0 0 0 0 5 0 0 0 0 0 0 
0 0 0 0 0 6 0 0 0 0 0 
0 0 0 0 0 0 7 0 0 0 0 
0 0 0 0 0 0 0 8 0 0 0 
0 0 0 0 0 0 0 0 9 0 0 
0 0 0 0 0 0 0 0 0 10 0 
0 0 0 0 0 0 0 0 0 0 11 
26.2 ns ± 0.539 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
25.9 ns ± 0.0734 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


2. Вводиться число n. Розставити 1 та 0 у шаховому
порядку, починаючи з 1 в матриці розміром n×n, використовуючи
слайсінг.

In [70]:
n = int(input("Enter size of matrix: "))
def t2np():
    matrix = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            if (i+j) % 2 == 0:
                matrix[i][j] = 1

    print(matrix)

def t2py():
    matrix = [[0 for j in range(n)] for i in range(n)]

    for i in range(n):
        for j in range(n):
            if (i+j) % 2 == 0:
                matrix[i][j] = 1

    for i in range(n):
        for j in range(n):
            print(matrix[i][j], end=" ")
        print()
        
t2np()
t2py()
%timeit t2np
%timeit t2py

Enter size of matrix: 13
[[1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]]
1 0 1 0 1 0 1 0 1 0 1 0 1 
0 1 0 1 0 1 0 1 0 1 0 1 0 
1 0 1 0 1 0 1 0 1 0 1 0 1 
0 1 0 1 0 1 0 1 0 1 0 1 0 
1 0 1 0 1 0 1 0 1 0 1 0 1 
0 1 0 1 0 1 0 1 0 1 0 1 0 
1 0 1 0 1 0 1 0 1 0 1 0 1 
0 1 0 1 0 1 0 1 0 1 0 1 0 
1 0 1 0 1 0 1 0 1 0 1 0 1 
0 1 0 1 0 1 0 1 0 1 0 1 0 
1 0 1 0 1 0 1 0 1 0 1 0 1 
0 1 0 1 0 1 0 1 0 1 0 1 0 
1 0 1 0 1 0 1 0 1 0 1 0 1 
26.4 ns ± 0.526 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops eac

4. Вводяться числа n і m. Вивести масив розміру n×m, в
якому у першому рядку (рядок з нулевим індексом) йдуть числа від 0
до m–1, а всі інші елементи матриці дорівнюють 0.

In [75]:
n = int(input("Enter number of rows: "))
m = int(input("Enter number of columns: "))

def t4np():
    matrix = np.zeros((n, m))
    matrix[0] = np.arange(m)

    print(matrix)

def t4py():
    matrix = []
    for i in range(n):
        row = []
        for j in range(m):
            row.append(0)
        matrix.append(row)
    
    for j in range(m):
        matrix[0][j] = j

    for i in range(n):
        for j in range(n):
            print(matrix[i][j], end=" ")
        print()
        
t4np()
t4py()
%timeit t4np
%timeit t4py

Enter number of rows: 13
Enter number of columns: 15
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
0 1 2 3 4 5 6 7 8 9 10 11 12 
0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 

7. З клавіатури вводиться масив. Замінити всі нульові
елементи на –1.

In [40]:
input_arr = np.array(input("Enter array of numbers separated by spaces: ").split(), dtype=np.int32)

def t7np():
    arr = input_arr
    arr[arr == 0] = -1

    print(arr)

def t7py():
    arr = input_arr

    for i in range(len(arr)):
        if arr[i] == 0:
            arr[i] = -1

    print(arr)
    
t7np()
t7py()
%timeit t7np
%timeit t7py

Enter array of numbers separated by spaces: 10 -8 55 48 -97 42 51 87 -36
[ 10  -8  55  48 -97  42  51  87 -36]
[ 10  -8  55  48 -97  42  51  87 -36]
26 ns ± 0.0859 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
29.8 ns ± 0.158 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


8. З клавіатури вводиться масив. Підрахувати в ньому
кількість нульових та ненульових елементів.

In [45]:
arr = input("Enter an array of numbers: ").split()

def t8np():
    ndarr = np.array(arr, dtype=int)
    num_non_zeros = np.count_nonzero(ndarr)
    num_zeros = ndarr.size - num_non_zeros

    print("Number of zeros:", num_zeros)
    print("Number of non-zeros:", num_non_zeros)

def t8py():
    array = arr
    count_zeros = 0
    count_non_zeros = 0
    
    for num in array:
        num = int(num)

        if num == 0:
            count_zeros += 1
        else:
            count_non_zeros += 1

    print("Number of zeros: ", count_zeros)
    print("Number of non-zeros: ", count_non_zeros)
    
t8np()
t8py()
%timeit t8np
%timeit t8py

Enter an array of numbers: 1 0 1 0 10 22 55 33 0 0 0
Number of zeros: 5
Number of non-zeros: 6
Number of zeros:  5
Number of non-zeros:  6
28.1 ns ± 0.335 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
26 ns ± 0.396 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


12. Створити масив одиниць розміром n×n та створити в
ньому «рамку», що утворюється з 0.

In [46]:
n = int(input("Enter size of matrix: "))

def t12np():
    arr = np.ones((n, n))
    arr[0,:] = 0
    arr[-1,:] = 0
    arr[:,0] = 0
    arr[:,-1] = 0
    print(arr)

def t12py():
    array = []
    for i in range(n):
        row = []
        for j in range(n):
            row.append(1)
        array.append(row)

    for i in range(n):
        for j in range(n):
            if i == 0 or i == n-1 or j == 0 or j == n-1:
                array[i][j] = 0

    for i in range(n):
        for j in range(n):
            print(array[i][j], end=" ")
        print()      

t12np()
t12py()
%timeit t12np
%timeit t12py

Enter size of matrix: 11
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
0 0 0 0 0 0 0 0 0 0 0 
0 1 1 1 1 1 1 1 1 1 0 
0 1 1 1 1 1 1 1 1 1 0 
0 1 1 1 1 1 1 1 1 1 0 
0 1 1 1 1 1 1 1 1 1 0 
0 1 1 1 1 1 1 1 1 1 0 
0 1 1 1 1 1 1 1 1 1 0 
0 1 1 1 1 1 1 1 1 1 0 
0 1 1 1 1 1 1 1 1 1 0 
0 1 1 1 1 1 1 1 1 1 0 
0 0 0 0 0 0 0 0 0 0 0 
25.9 ns ± 0.175 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
25.8 ns ± 0.168 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


15. Заповнити парні стовпчикі матриці розміром n×n
одиницями, а непарні – нулями.

In [47]:
n = int(input("Enter size of matrix: "))

def t15np():
    arr = np.zeros((n, n), dtype=int)
    for i in range(n):
        if i % 2 == 1:
            arr[:,i] = 1

    print(arr)

def t15py():
    arr = []
    for i in range(n):
        row = []
        for j in range(n):
            row.append(0)
        arr.append(row)

    for i in range(n):
        for j in range(n):
            if j % 2 == 0:
                arr[i][j] = 1
            else:
                arr[i][j] = 0

    for i in range(n):
        for j in range(n):
            print(arr[i][j], end=" ")
        print()
        
t15np()
t15py()
%timeit t15np
%timeit t15py

Enter size of matrix: 10
[[0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]]
1 0 1 0 1 0 1 0 1 0 
1 0 1 0 1 0 1 0 1 0 
1 0 1 0 1 0 1 0 1 0 
1 0 1 0 1 0 1 0 1 0 
1 0 1 0 1 0 1 0 1 0 
1 0 1 0 1 0 1 0 1 0 
1 0 1 0 1 0 1 0 1 0 
1 0 1 0 1 0 1 0 1 0 
1 0 1 0 1 0 1 0 1 0 
1 0 1 0 1 0 1 0 1 0 
25.9 ns ± 0.182 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
26.2 ns ± 0.676 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


16. Заповнити вектор значеннями від 0 до n. Всі значення,
що більші за n/4 та менші за 3n/4 замінити нулями.

In [15]:
n = int(input("Enter value for n: "))

def t16np():
    arr = np.arange(n+1)
    arr[(arr > n/4) & (arr < 3*n/4)] = 0

    print(arr)

def t16py():
    array = [0] * n

    for i in range(n):
        array[i] = i

    for i in range(n):
        if n/4 < array[i] < 3*n/4:
            array[i] = 0

    print(array)
    
t16np()
t16py()
%timeit t16np
%timeit t16py

Enter value for n: 15
[ 0  1  2  3  0  0  0  0  0  0  0  0 12 13 14 15]
[0, 1, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 12, 13, 14]


20. Згенерувати вектор із n випадкових елементів, що
лежать в інтервалі (0,1). Замінити максимальний елемент на 0.

In [48]:
import random

n = int(input("Enter size of vector: "))

def t20np():
    vec = np.random.rand(n)
    print("Original vector:\n", vec)
    max_idx = np.argmax(vec)
    vec[max_idx] = 0

    print("Modified vector:\n", vec)

def t20py():
    vec = [0] * n

    for i in range(n):
        vec[i] = random.random()

    print("Original vector:", vec)

    max_index = 0
    for i in range(1, n):
        if vec[i] > vec[max_index]:
            max_index = i

    vec[max_index] = 0

    print("Modified vector:\n", vec)
    
t20np()
t20py()
%timeit t20np
%timeit t20py

Enter size of vector: 13
Original vector:
 [0.64940731 0.51682009 0.77368717 0.65734221 0.32415933 0.15556221
 0.68504987 0.4372911  0.27287579 0.8802654  0.13623482 0.20455666
 0.49796307]
Modified vector:
 [0.64940731 0.51682009 0.77368717 0.65734221 0.32415933 0.15556221
 0.68504987 0.4372911  0.27287579 0.         0.13623482 0.20455666
 0.49796307]
Original vector: [0.8196905722986819, 0.02951030793594822, 0.1387170951720721, 0.6705826771143365, 0.46535609796830524, 0.417530146905599, 0.7012052124056577, 0.25503984248546163, 0.847228262392911, 0.26151714593112707, 0.865316116088705, 0.3729823737899891, 0.06559883552175683]
Modified vector:
 [0.8196905722986819, 0.02951030793594822, 0.1387170951720721, 0.6705826771143365, 0.46535609796830524, 0.417530146905599, 0.7012052124056577, 0.25503984248546163, 0.847228262392911, 0.26151714593112707, 0, 0.3729823737899891, 0.06559883552175683]
25.9 ns ± 0.295 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
25.9 ns ± 0.144 ns p

In [31]:
A = np.array([[1, 2, 1, 1], [2, 1, 1, 1], [1, -1, 2, 1], [1, 1, -1, 3]], dtype=float)
b = np.array([8, 5, -1, 10], dtype=float)

detA = np.linalg.det(A)

if abs(detA) < 1e-9:
    print("Determinant of A is zero. The system of equations may not have a unique solution.")
else:
    cramer = np.zeros(4)
    for i in range(4):
        A_c = A.copy()
        A_c[:,i] = b
        detA_c = np.linalg.det(A_c)
        cramer[i] = detA_c / detA
    
for i in range(len(x2)):
    print(f"x_{i+1} = {cramer[i]}")
    
Ax = np.dot(A, cramer)
print("Check solution using matrix multiplication:")
print(Ax)

x_1 = -0.05263157894736883
x_2 = 2.9473684210526305
x_3 = -0.15789473684210534
x_4 = 2.3157894736842115
Check solution using matrix multiplication:
[ 8.  5. -1. 10.]


In [25]:
x1 = np.linalg.inv(A) @ b

print("The solution is:")
for i in range(len(x1)):
    print(f"x_{i+1} = {x1[i]}")

The solution is:
x_1 = -0.05263157894736892
x_2 = 2.947368421052632
x_3 = -0.15789473684210553
x_4 = 2.3157894736842106


In [26]:
x2 = np.linalg.solve(A, b)

print("The solution is:")
for i in range(len(x2)):
    print(f"x_{i+1} = {x2[i]}")

The solution is:
x_1 = -0.05263157894736836
x_2 = 2.9473684210526314
x_3 = -0.1578947368421053
x_4 = 2.3157894736842106


In [79]:
xx1_equal = np.allclose(x, x1, rtol=1e-2)
xx2_equal = np.allclose(x, x2, rtol=1e-2)
x1x2_equal = np.allclose(x1, x2, rtol=1e-2)
cramerx_equal = np.allclose(cramer, x, rtol=1e-2)
cramerx1_equal = np.allclose(cramer, x1, rtol=1e-2)
cramerx2_equal = np.allclose(cramer, x2, rtol=1e-2)

# Print the results
print(f"Array x and array x1 are equal: {xx1_equal}")
print(f"Array x and array x2 are equal: {xx2_equal}")
print(f"Array x1 and array x2 are equal: {x1x2_equal}")
print(f"Array cramer and array x are equal: {cramerx_equal}")
print(f"Array cramer and array x1 are equal: {cramerx1_equal}")
print(f"Array cramer and array x2 are equal: {cramerx2_equal}")

Array x and array x1 are equal: True
Array x and array x2 are equal: True
Array x1 and array x2 are equal: True
Array cramer and array x are equal: True
Array cramer and array x1 are equal: True
Array cramer and array x2 are equal: True


In [63]:
A = np.array([[1, 4, 2], [2, 1, -2], [0, 1, -1]])
B = np.array([[4, 6, -2], [4, 10, 1], [2, 4, -5]])

def task3np():
    expressionNP = 2*A - (A@A + B)@B
    return expressionNP

expressionNP = task3np()
print("Result:")
print(expressionNP)

Result:
[[ -94 -190  -36]
 [-106 -236   20]
 [ -20  -38  -28]]


In [64]:
def matmul(A, B):
    n = len(A)
    
    C = np.full((n, n), 0)
    for i in range(n):
        for j in range(n):
            for k in range(n):
                C[i][j] += A[i][k] * B[k][j]
    return C

def matscale(A, scalar):
    n = len(A)
    C = np.full((n, n), 0)
    for i in range(n):
        for j in range(n):
            C[i][j] = A[i][j] * scalar
    return C

def matadd(A, B):
    n = len(A)
    C = np.full((n, n), 0)
    for i in range(n):
        for j in range(n):
            C[i][j] = A[i][j] + B[i][j]
    return C

def matsub(A, B):
    n = len(A)
    C = np.full((n, n), 0)
    for i in range(n):
        for j in range(n):
            C[i][j] = A[i][j] - B[i][j]
    return C

def task3py():
    expressionBrut = matsub(matscale(A, 2), matmul(matadd(matmul(A, A), B), B))
    return expressionBrut

expressionBrut = task3py()
print("Result:")
print(expressionBrut)

Result:
[[ -94 -190  -36]
 [-106 -236   20]
 [ -20  -38  -28]]


In [65]:
mat_equal = np.allclose(expressionNP, expressionBrut, rtol=1e-2)
print(f"Array expressionNP and array expressionBrut are equal: {mat_equal}")

%timeit task3np()
%timeit task3py()

Array expressionNP and array expressionBrut are equal: True
4.96 µs ± 47 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
79.7 µs ± 330 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
